Make scann range search results more accurate
zilliztech/knowhere pull request #179
Opened 2023-11-06 10:09 UTC by chasingegg

Related #171 
Range search's recall of ScaNN is poor due to quantization. Enlarge radius to take more candidates into consideration.

2023-11-06 10:10 UTC, chasingegg commented
/hold

2023-11-06 15:03 UTC, alexanderguzhva requested changes

2023-11-06 15:03 UTC, alexanderguzhva commented on thirdparty/faiss/faiss/IndexIVFPQFastScan.cpp
> +    float radius_thresh = C::is_max ? radius * 1.2 : radius * 0.6;  // to make range search result more accurate
Such a change should never be done on the Faiss side, but on the Knowhere side. Please move it to `ivf.cc`.

2023-11-20 09:15 UTC, chasingegg commented
close this, need further investigation

2023-11-20 09:15 UTC, closed without merging