support build cardinal as a plugin
zilliztech/knowhere pull request #365
Opened 2024-01-26 08:59 UTC by foxspy

issue: #364

2024-01-26 08:59 UTC, foxspy commented
/hold

2024-01-31 21:47 UTC, alexanderguzhva commented
Is it a general-purpose plugin system or just a mechanism for optionally attaching Cardinal? If the first one, then how many plugins are we supposed to have? If it is for Cardinal only, then why a plain 
```
#ifdef USE_CARDINAL
#include "cardinal/cardinal.h"
REGISTER_CARDINAL(whatever)
#endif
```
is not sufficient?

2024-02-01 14:51 UTC, foxspy commented
> Is it a general-purpose plugin system or just a mechanism for optionally attaching Cardinal? If the first one, then how many plugins are we supposed to have? If it is for Cardinal only, then why a plain
> 
> ```
> #ifdef USE_CARDINAL
> #include "cardinal/cardinal.h"
> REGISTER_CARDINAL(whatever)
> #endif
> ```
> 
> is not sufficient?

We will support not only cardinal. Someone can integrate their own indexes into knowhere without additional development work once their indexes obey the interface rule.

2024-02-01 22:52 UTC, alexanderguzhva requested changes
A couple of things to fix. Otherwise, looks good :)

2024-02-01 22:52 UTC, alexanderguzhva commented on src/common/comp/knowhere_config.cc
> +        auto splitPaths = [&](std::string input, char delimiter) {
Please use `std::filesystem` facilities for this

2024-02-01 22:52 UTC, alexanderguzhva commented on src/common/comp/knowhere_config.cc
> +            void* plugin = dlopen(lib.c_str(), RTLD_NOW | RTLD_GLOBAL);
I could not find the corresponding `dlclose()`

2024-03-13 06:27 UTC, closed without merging