Replace gettid() with syscall(SYS_gettid)
zilliztech/knowhere pull request #396
Opened 2024-02-20 07:01 UTC by zhengbuqian

in some older glibc version gettid() wrapper does not exist.

issue: #394

2024-02-20 08:26 UTC, zhengbuqian commented
/run-e2e

2024-02-20 09:39 UTC, zhengbuqian commented
/kind improvement

2024-02-20 09:40 UTC, zhengbuqian commented
issue: #394

2024-02-20 18:12 UTC, alexanderguzhva requested changes

2024-02-20 18:12 UTC, alexanderguzhva commented on include/knowhere/comp/thread_pool.h
> +                if (setpriority(PRIO_PROCESS, static_cast<pid_t>(syscall(SYS_gettid)), 19) != 0) {
I'd rather go with the following solution
```
#if __GLIBC__ == 2 && __GLIBC_MINOR__ < 30
#include <sys/syscall.h>
#define gettid() syscall(SYS_gettid)
#endif
```
as suggested https://stackoverflow.com/questions/30680550/c-gettid-was-not-declared-in-this-scope/

2024-02-21 12:05 UTC, alexanderguzhva commented
/lgtm

2024-02-21 13:16 UTC, zhengbuqian commented
/run-e2e

2024-02-22 02:50 UTC, merged