Add iterator for ivf_sq_8
zilliztech/knowhere pull request #414
Opened 2024-02-27 06:26 UTC by cqy123456

2024-02-27 06:29 UTC, cqy123456 commented on thirdparty/faiss/faiss/IndexIVF.cpp
> +                scanner->set_list(list_no, coarse_list_centroid_dist);
add a line :  add centroid id and distance for quantizer.

2024-02-27 08:12 UTC, zhengbuqian reviewed
thanks!

2024-02-27 08:12 UTC, zhengbuqian commented on thirdparty/faiss/faiss/impl/ScalarQuantizerScanner.h
> +            counter_back ++;
nit: space

2024-02-27 08:12 UTC, zhengbuqian commented on thirdparty/faiss/faiss/impl/ScalarQuantizerScanner.h
> +    }
missing return statement.

2024-02-27 08:12 UTC, zhengbuqian commented on thirdparty/faiss/faiss/IndexIVF.cpp
> +                    size_t n_heap = scanner->scan_codes_and_push_back(
temp variable n_heap is not used. discussed with @alwayslove2013 and we can remove it.

2024-02-28 08:32 UTC, zhengbuqian commented on thirdparty/faiss/faiss/IndexIVF.cpp
> +                    size_t n_heap = scanner->scan_codes_and_push_back(
sorry for being not precise in the previous comment: I meant to simply remove this local variable while `scan_codes_and_push_back` can still keep the return value for future use(could be used for metrics) and to have a aligned behavior with `scan_codes`.

2024-03-06 18:26 UTC, alexanderguzhva requested changes

2024-03-06 18:26 UTC, alexanderguzhva commented on thirdparty/faiss/faiss/IndexIVF.cpp
> +        size_t nprobe = workspace->search_params->nprobe
what if `workspace->search_params` is `nullptr`?

2024-03-06 18:26 UTC, alexanderguzhva commented on thirdparty/faiss/faiss/IndexIVF.cpp
> +    auto scan_one_list_then_add_to_backup =
please add a check if `workspace` is `nullptr`

2024-03-06 18:26 UTC, alexanderguzhva commented on thirdparty/faiss/faiss/IndexIVF.h
> +struct IVFIteratorWorkspace {
Please add very detailed comments on what this structure does exactly and how it is used

2024-03-06 18:26 UTC, alexanderguzhva commented on thirdparty/faiss/faiss/IndexIVF.h
> +    std::unique_ptr<IVFIteratorWorkspace> getIteratorWorkspace(
Please add comments for this method about what it does

2024-04-16 10:07 UTC, zhengbuqian commented
please hold until https://github.com/zilliztech/knowhere/pull/501 is merged. It slightly changed how we should implement iterator for indexes. It should make this PR much simpler.

2024-07-22 01:56 UTC, closed without merging