remove seed_ef and use ef for hnsw iterator
zilliztech/knowhere pull request #599
Opened 2024-05-24 07:17 UTC by zhengbuqian

2024-05-24 07:22 UTC, zhengbuqian commented
kind/improvement

issue: #500

2024-05-24 08:45 UTC, alwayslove2013 requested changes

2024-05-24 08:45 UTC, alwayslove2013 commented on src/index/hnsw/hnsw_config.h
>              .for_search()
seems that `ef` need for_iterator

2024-05-24 08:51 UTC, zhengbuqian commented on src/index/hnsw/hnsw_config.h
>              .for_search()
good catch!

2024-05-27 01:49 UTC, alwayslove2013 commented
/lgtm

2024-05-27 02:34 UTC, zhengbuqian commented
kind/improvement

issue: https://github.com/zilliztech/knowhere/issues/500

2024-05-27 02:35 UTC, cydrain commented
/kind improvement

2024-05-27 02:47 UTC, merged