Set norm to 1.0 for all-0 vectors
zilliztech/knowhere pull request #803
Opened 2024-08-30 08:45 UTC by cydrain

2024-08-30 08:45 UTC, cydrain commented
/kind improvement
/hold

2024-08-30 14:29 UTC, alexanderguzhva requested changes

2024-08-30 14:29 UTC, alexanderguzhva commented on thirdparty/faiss/faiss/IVFlib.cpp
> +                norm = (norm == 0.0 ? 1.0 : norm);
no, because it uses norm for `distance = x^2 - 2xy + y^2` calculation, not for a cosine-related code

2024-08-30 14:29 UTC, alexanderguzhva commented on thirdparty/faiss/faiss/IndexAdditiveQuantizer.cpp
> +            bias = (bias == 0.0 ? 1.0 : bias);
no, because it uses norm for distance = x^2 - 2xy + y^2 calculation, not for a cosine-related code

2024-08-30 14:29 UTC, alexanderguzhva commented on thirdparty/faiss/faiss/IndexAdditiveQuantizer.cpp
> +            bias = (bias == 0.0 ? 1.0 : bias);
no, because it uses norm for distance = x^2 - 2xy + y^2 calculation, not for a cosine-related code

2024-08-30 14:29 UTC, alexanderguzhva commented on thirdparty/faiss/faiss/IndexFlat.cpp
> +        query_l2norm = (query_l2norm == 0.0 ? 1.0 : query_l2norm);
no, because it uses norm for distance = x^2 - 2xy + y^2 calculation, not for a cosine-related code

2024-08-30 14:29 UTC, alexanderguzhva commented on thirdparty/faiss/faiss/IndexIVFAdditiveQuantizer.cpp
> +            distance_bias = (distance_bias == 0.0 ? 1.0 : distance_bias);
no, because it uses norm for distance = x^2 - 2xy + y^2 calculation, not for a cosine-related code

2024-08-30 14:29 UTC, alexanderguzhva commented on thirdparty/faiss/faiss/IndexIVFPQ.cpp
> +            r_norms[m * pq.ksub + j] = (norm == 0.0 ? 1.0 : norm);
no, because it uses norm for distance = x^2 - 2xy + y^2 calculation, not for a cosine-related code

2024-08-30 14:29 UTC, alexanderguzhva commented on thirdparty/faiss/faiss/impl/AdditiveQuantizer.cpp
> +            norms[i] = (norm == 0.0 ? 1.0 : norm);
no, because it uses norm for distance = x^2 - 2xy + y^2 calculation, not for a cosine-related code

2024-08-30 14:29 UTC, alexanderguzhva commented on thirdparty/faiss/faiss/utils/distances.cpp
> +        auto norm = fvec_norm_L2sqr(x + i * d, d);
no, because it might use norm for distance = x^2 - 2xy + y^2 calculation, not for a cosine-related code

2024-08-30 14:29 UTC, alexanderguzhva commented on thirdparty/faiss/faiss/utils/distances.cpp
> +        nr[i] = (norm == 0.0 ? 1.0 : norm);
no, because it might use norm for distance = x^2 - 2xy + y^2 calculation, not for a cosine-related code

2024-08-30 14:29 UTC, alexanderguzhva commented on thirdparty/faiss/faiss/utils/distances.cpp
> +                norm = (norm == 0.0 ? 1.0 : norm);
yes

2024-08-30 14:29 UTC, alexanderguzhva commented on thirdparty/faiss/faiss/utils/distances.cpp
> +            norm = (norm == 0.0 ? 1.0 : norm);
yes

2024-09-03 14:10 UTC, alexanderguzhva commented
/lgtm

2024-09-03 14:10 UTC, alexanderguzhva commented
@cydrain does it solve https://github.com/milvus-io/milvus/issues/35594 ?

2024-09-03 15:08 UTC, alexanderguzhva commented
/unhold

2024-09-03 15:08 UTC, merged

2024-09-04 02:01 UTC, cydrain commented
> @cydrain does it solve [milvus-io/milvus#35594](https://github.com/milvus-io/milvus/issues/35594) ?

Yes, milvus#35594 will be fixed with this PR