Remove f16c flag in utils_sse
zilliztech/knowhere pull request #814
Opened 2024-09-05 02:40 UTC by cqy123456

2024-09-05 10:50 UTC, alexanderguzhva requested changes

2024-09-05 10:50 UTC, alexanderguzhva commented on src/simd/hook.cc
> -
I would keep this function just in case

2024-09-05 10:50 UTC, alexanderguzhva commented on src/simd/distances_sse.cc
> +    std::vector<knowhere::fp32> fp32_x(d);
`std::vector` introduces an enormous overhead.
Please implement these functions manually in the following way:
```
    float res = 0;
    for (size_t i = 0; i < d; i++) {
        const float xv = float(x[i]);
        res += xv * xv;
    }

    return res;
``` 
Similar for dot products

2024-09-05 10:50 UTC, alexanderguzhva commented on src/simd/hook.h
> -bool
I'd keep this function

2024-09-05 12:22 UTC, alexanderguzhva commented
@cqy123456 We can use `_ref` versions, sure. But the downside is that a compiler will not use `sse` instructions for compiling `ref` versions, such a change introduces a performance regression. Therefore, the most optimal way is to literally copy-paste `ref` versions code into `distances_sse.cc` under new function names, because it allows a compiler to use `sse` instructions. 
It is not a big problem if we're going to have small pieces of the same code in different files.

2024-09-06 03:09 UTC, cqy123456 commented
At first I tried to only rely on compiler optimization, but the compiler did not speed up fp16's (float)x * (float)y very well, probably because the fp16->float operation is more complicated.

2024-09-06 09:25 UTC, PwzXxm commented
/lgtm
Patch to release for correctness first.

2024-09-06 09:27 UTC, merged